import type { Metadata } from "next";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "./globals.css";
import { ConversionProvider } from "@/context";
import Head from "next/head";



export const metadata: Metadata = {
  title: "YapUp - Chat App",
  keywords: ["Chat", "App", "YapUp", "Next.js", "Clerk"],
  authors: [{ name: "YapUp Team", url: "http://localhost.com" }],
  creator: "YapUp Team",
  openGraph: {
    title: "YapUp - Chat App",
    description: "A modern chat application built with Next.js and Clerk",
    url: "http://localhost.com",
    siteName: "YapUp",
    images: [
      {
        url: "http://localhost.com",
        width: 1200,
        height: 630,
        alt: "YapUp Chat App",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <ClerkProvider>
    <ConversionProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="favicon.ico"  />
        </head>
        <body>

          {children}
        </body>
      </html>
      </ConversionProvider>
    </ClerkProvider>
  );
}
